"""
Bootstrap compiler for a Python-like language that targets ARM assembly.
This is a minimalist implementation focused on demonstrating the process.
Generated by Claude 3.7
"""

import re
import sys
from enum import Enum, auto
from typing import List, Dict, Union, Optional, Tuple
from src.lexer import Lexer
from src.parser import Parser
from src.ir import IRGenerator
from src.generators.mc_gen import MachineCodeGenerator


###############################################################################
# PART 6: COMPILER DRIVER - Main program that ties everything together
###############################################################################


def compile_code(source_code: str, architecture: str = "arm") -> str:
    """Compile source code to target machine code"""
    # Stage 1: Lexing
    lexer = Lexer(source_code)
    tokens = lexer.tokenize()

    print("-----TOKENS-----")
    print(tokens)

    # Stage 2: Parsing
    parser = Parser(tokens)
    ast = parser.parse()

    print("-----AST-----")
    print(ast)

    # Stage 3: IR Generation
    ir_gen = IRGenerator()
    ir = ir_gen.generate(ast)

    print("-----IR-----")
    print(ir)

    # Stage 4: Target Code Generation
    code_gen = MachineCodeGenerator(architecture)
    target_code = code_gen.generate(ir)

    return target_code
